[0.10] - Added check-invalid-reads
phalcon/zephir-docs pull request #161
Opened 2018-11-04 17:17 UTC by niden

Added verbiage for `check-invalid-reads`

2018-11-04 17:17 UTC, niden commented
cc @sergeyklay  @danhunsaker Input please

2018-11-05 01:01 UTC, sergeyklay requested changes

2018-11-05 01:01 UTC, sergeyklay commented on en/optimizations.md
> +        var i = NULL;
```suggestion
        var i = null;
```

2018-11-05 02:34 UTC, danhunsaker reviewed
Nothing to add, other than to ask whether we just removed this one, recently, and if so, whether the old verbiage was used as a starting point, here?

2018-11-05 13:02 UTC, niden commented
@danhunsaker We removed it by mistake (my bad). The old verbiage was really the first sentence. I added a bit more to explain what this option does.

2018-11-05 13:04 UTC, merged